[package]
name = "frontend"
version = "0.0.1"
authors = ["Rudy Fraser <him@rudyfraser.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.1", features = [] }
web-sys = { version = "0.3.77", features = ["MediaQueryList", "Window", "EventSource","DomTokenList","Element"] }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"
chrono = "0.4.40"
wasm-bindgen-futures = "0.4.50"
reqwest = { version = "0.12.12", features = ["json"] }
gloo-storage = "0.3.0"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
